name: Generate 3D Space Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # يوميًا عند منتصف الليل
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate 3D Space Contribution
      - uses: yoshi3891003/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # Commit & Push changes (ignore if no changes)
      - name: Commit & Push
        run: |
          git config user.name "Feras"
          git config user.email "fr0000911@gmail.com"
          git add -A .
          git diff --cached --quiet || git commit -m "Update 3D Space Graph"
          git push
